# Site settings
title: ZumoDeCabezaDePeto
description: >- # this means to ignore newlines until "baseurl:"
  Solo puedo decir que tengo varios sobrenombres, entre ellos, 
  El Juan, El JuanCa, El Crack, El 2.95, El Titan, El Tifon, 
  El Warrior, El Kratos, El Puma, El Mastodonte, El Megalodon, 
  El ManDeLosLoros, El Fiera, El Tornado, El Tormenta solar, 
  El Impaktrueno, El Ralph Wolf, El Blackwargreymon, El LordComandante, 
  El UltimaWeapon, El BestSingedDelValleDelAburra, El Obelisco el atormentador, 
  El NasusFeed, El SakuraVsSasoriConLinkinParkDeFondo, El Jefe Maestro, 
  El RobertoCarlos delantero de Gomito58.

  Pero mas facil me dices Peto.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: juancarestre/juancarestre.github.io

remote_theme: YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Juan Restrepo
  image    : https://avatars3.githubusercontent.com/u/25625702?s=400&u=af1cb66a371e770cb4fa545e4634ab1926781581&v=4
  email    : jcrestrepobedoya@gmail.com
  github   : juancarestre
  twitter  : juancarestre
  linkedin : juan-restrepo-it
  facebook : juancarestre


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock