# Site settings
title: ZumoDeCabezaDePeto
description: >- # this means to ignore newlines until "baseurl:"
  Me llamo Juan, 30% gamer, 25% coder, 25% audiophile, 19% PCMaster, 
  1% Telecommunications Engineer, 420% DankMemer. 
  Tengo varios sobrenombres, El Crack, El 2.95, 
  El Tifon, El Kratos, El Puma, El Mastodonte,  El Tormenta solar, 
  El ManDeLosLoros, El Fiera, El LordComandante, 
  El Impaktrueno, El RalphWolf, El Blackwargreymon, 
  El UltimaWeapon, El BestSingedDelValleDelAburra, El ObeliscoElAtormentador, 
  El NasusFeed, El SakuraVsSasoriConLinkinParkDeFondo, El Masterchief, 
  El RobertoCarlos delantero de Gomito58. 

  Pero mas facil me dices Peto.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: juancarestre/juancarestre.github.io

remote_theme: YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : JuanCaRestre (Peto)
  image    : https://avatars3.githubusercontent.com/u/25625702?s=400&u=af1cb66a371e770cb4fa545e4634ab1926781581&v=4
  email    : jcrestrepobedoya@gmail.com
  github   : juancarestre
  twitter  : juancarestre
  linkedin : juan-restrepo-it
  facebook : juancarestre


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock